FROM node:18-alpine

WORKDIR /app

# Install Sharp and other dependencies
RUN apk add --no-cache python3 make g++ vips-dev

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

CMD ["node", "index.js"]
